#!/bin/bash

# compileProg - A script to compile the executable

help()
{
  echo "Script to create executable"
  echo "Requires cmake and a fortran compiler"
  echo "By the default gnu compilers are used"
  echo "" 
  echo "usage: createHIREexec [-f compiler] [-d] | [-h]"
  echo ""
  echo "-d - Debug version"
  echo "-f - Fortran compiler - specify the compiler (default: gfortran)"
  echo "-h - Display this help"
}

## Main installer
fcompiler="gfortran"
buildtype="Release"

#parse the options provided
while [ "$1" != "" ]; do
	case $1 in 
	-f | --fortran )  shift
		          fcompiler="$1"
			  ;;
	-d | --debug ) buildtype="Debug"
		       ;;
        -h | --help ) help
		      exit
		      ;;
	* ) help
	    exit 1
esac
shift
done

#set directory name and set up directory
current="$(pwd)"

if [ -d build ]; then
        cd build
	rm -rf *
else
	mkdir -p build
	cd build
fi

FC=$fcompiler cmake ../src -DCMAKE_BUILD_TYPE=$buildtype 

make

cp  PitchAngles $current/

cd $current
exit
